### PR TITLE
Added the option to supply a description when creating a vlan

### PR DESCRIPTION
**Pull request by JaySystem**
Allow for the description field to be passed when creating a new VLAN

### CODE REVIEW

**Comment by karmab** [comment]
@JaySystem to fix the linting issue in CI, you need to make black api with the following formatting for create vlan

```
def create_vlan(
self, project_id, facility, vxlan=None, vlan=None, description=None
):
```

**Comment by JaySystem** [comment]
> @JaySystem to fix the linting issue in CI, you need to make black api with the following formatting for create vlan
> 
> ```
> def create_vlan(
> self, project_id, facility, vxlan=None, vlan=None, description=None
> ):
> ```

Thanks for trying to help me not fail but I'm clearly destined to. I have taken your suggestion on the formatting but still getting issues

**Comment by displague** [comment]
@JaySystem This project uses [drone](https://github.com/packethost/packet-python/blob/master/.drone.yml) to lint and test the repo.  The configured linter in that drone config is [`black`](https://black.readthedocs.io/en/stable/).

Try installing `black`, with `pip3 install black` (or include `--user`).

You should then be able to get the precise listing that Drone/Black expects with:

```
$ black packet/Manager.py 
All done! ✨ 🍰 ✨
1 file left unchanged.
```

I ran this against your branch and indentation at [lines 35-36 here](https://drone.packet.net/packethost/packet-python/296/19) is the culprit.

Please squash this PR down to a single commit in the next push. Thanks for this contribution and for bearing with us!

**Comment by JaySystem** [comment]
> @JaySystem This project uses [drone](https://github.com/packethost/packet-python/blob/master/.drone.yml) to lint and test the repo. The configured linter in that drone config is [`black`](https://black.readthedocs.io/en/stable/).
> 
> Try installing `black`, with `pip3 install black` (or include `--user`).
> 
> You should then be able to get the precise linting that Drone/Black expects with:
> 
> ```
> $ black packet/Manager.py 
> All done! ✨ 🍰 ✨
> 1 file left unchanged.
> ```
> 
> I ran this against your branch and indentation at [lines 35-36 here](https://drone.packet.net/packethost/packet-python/296/19) is the culprit.
> 
> Please squash this PR down to a single commit in the next push. Thanks for this contribution and for bearing with us!

Hi displague,

Thanks for the information well after that as you can seen I have tried again. I have enabled black as the formatted type on vscode and also ran black against Mananger.py which still gave me the wrong formatting for some reason. 

` def create_vlan(
      self, project_id, facility, vxlan=None, description=None, vlan=None
    ):` 

This is the outcome I get after running black and also with trying the vscode setting

**Comment by displague** [comment]
@JaySystem It was staring me in the face... There is a stray comma at the end of the line. 👓 
Please squash this down to a single commit for the PR.
With those two changes, this looks good to me.

---

If you click on the CI details, find the failed build, click on the failed build step, it shows this:

```patch
--- packet/Manager.py	2020-06-22 09:46:34.231556 +0000
+++ packet/Manager.py	2020-06-22 09:46:39.936301 +0000
@@ -537,11 +537,11 @@
             vlans.append(Vlan(vlan, self))
 
         return vlans
 
     def create_vlan(
-        self, project_id, facility, vxlan=None, description=None, vlan=None,
+        self, project_id, facility, vxlan=None, description=None, vlan=None
     ):
         params = {
             "project_id": project_id,
             "facility": facility,
             "vxlan": vxlan,
```

**Comment by displague** [comment]
I updated this PR with the linting changes and squashed commits.  I moved the `description` arg was moved to the end of the arg list to avoid any problems for existing users.

The linter is passing.

Thanks again, @JaySystem!

**Pull request merged**
