### PR TITLE
Add storage feature to create_device

### PR DESCRIPTION
**Pull request by obynio**
We need to be able to do custom partitioning on our machines.
This PR add this feature.

### CODE REVIEW

**Comment by jasmingacic** [comment]
This is looking good.

**Comment by jasmingacic** [comment]
@obynio  Can you please run the live tests for the device and paste the results here, before we merge it.

**Comment by obynio** [comment]
Sure, I'll do that tomorrow. Note that this feature can only be used if you have a hardware reservation.

**Comment by obynio** [comment]
Python script:
```
import packet
manager = packet.Manager(auth_token="yourapiauthtoken")

storage = {
  "disks": [
    {
      "device": "/dev/sda",
      "wipeTable": True,
      "partitions": [
        {
          "label": "BIOS",
          "number": 1,
          "size": 4096
        },
        {
          "label": "SWAP",
          "number": 2,
          "size": "3993600"
        },
        {
          "label": "ROOT",
          "number": 3,
          "size": 0
        }
      ]
    }
  ],
  "filesystems": [
    {
      "mount": {
        "device": "/dev/sda3",
        "format": "ext4",
        "point": "/",
        "create": {
          "options": [
            "-L",
            "ROOT"
          ]
        }
      }
    },
    {
      "mount": {
        "device": "/dev/sda2",
        "format": "swap",
        "point": "none",
        "create": {
          "options": [
            "-L",
            "SWAP"
          ]
        }
      }
    }
  ]
}

device = manager.create_device(project_id='project-id, hardware_reservation_id='hardware-reservation-id',
                               hostname='test',
                               plan='t1.small.x86', facility='ewr1',
                               operating_system='ubuntu_16_04', storage=storage)

print(device.created_at)
```

Successful creation:
```
$ python3 create.py
2019-10-16T13:13:51Z
```

**Comment by leenux-arch** [comment]
Sorry, here is the live test output.
```
(cli) ~/packet-python $ python -m unittest discover test                                                                                                                                                                                                                                                                                                           (cli)
ssssssssssssssssssssss...................................sssssssssssssssssssss
----------------------------------------------------------------------
Ran 78 tests in 0.096s

OK (skipped=43)
```

**Comment by obynio** [comment]
Sorry, here is the live test output.
```
(cli) ~/packet-python ❯❯❯ python -m unittest discover test                                                                                                                                                                                                                                                                                                           (cli)
ssssssssssssssssssssss...................................sssssssssssssssssssss
----------------------------------------------------------------------
Ran 78 tests in 0.096s

OK (skipped=43)
```

**Comment by jasmingacic** [comment]
Can you first set `PACKET_AUTH_TOKEN` then run the tests?

**Comment by obynio** [comment]
Mhhh, I have trouble to understand why we need this since the CI is already running the tests.
Unfortunately I cannot run these tests using my company packet account.

I ran that but I doubt that's what you need.
```
(cli) ~/packet-python $ PACKET_AUTH_TOKEN='faketoken' python -m unittest discover test                                                                                                                                                                                                                                                                             (cli)
ssssssssssssssssssssss...................................sssssssssssssssssssss
----------------------------------------------------------------------
Ran 78 tests in 0.102s

OK (skipped=43)
```

**Comment by jasmingacic** [comment]
The CI is not running live tests. 
I will merge this and if there is a need to have it fixed you will know.
Thanks anyways

**Pull request merged**
