### PR TITLE
add spot instance support

### PR DESCRIPTION
**Pull request by suihkulokki**
A very basic implementation. Adds the needed variables to create_device, fixing #30 and adds a new get_spot_market_prices() function.

---
This change is [Reviewable](https://reviewable.io/reviews/packethost/packet-python/31)

### CODE REVIEW

**Comment by suihkulokki** [comment]
Corrects the obvious mistake of not using .get for optional variables in Device(). The checks succeed locally now, but checks failing in travis seem not more like test env problem.

**Comment by AmineChikhaoui** [comment]
Hey folks, anything left for this to be merged ? I've been using this for a while for some testing of NixOps project and didn't see issues.

**Comment by mmlb** [comment]
Hmm not that I can tell, I'll get this merged this week/likely tomorrow.

**Comment by mmlb** [comment]
@suihkulokki I added termination_time in a separate commit and merged, thanks!

**Pull request closed without merging**
