### PR TITLE
Add hardware-reservations support

### PR DESCRIPTION
**Pull request by obynio**
Add hardware reservation to the python client.
The `/facilities` endpoint can not get a particular endpoint yet so I commented that part.

### CODE REVIEW

**Comment by jasmingacic** [comment]
Can you please add unit test for `list_hardware_reservations` and what kind of error were you getting from `/facilities` endpoint?

**Comment by jasmingacic** [comment]
Also can you please check the output of the CI.
Make sure that you run `pylama` to verify formatting and syntax like show [here](https://github.com/packethost/packet-python/blob/master/.drone.yml#L10-L15)

**Comment by obynio** [comment]
Sure, will do asap. I hope they have some reserved hardware tied to their API token so we can test the feature.

**Comment by obynio** [comment]
Concerning the `/facilities` endpoint, it can list all endpoint but can not show a particular endpoint with `/facilities/{{facility_id}}`. They are aware of it and will fix it in the future.

**Comment by jasmingacic** [comment]
Thanks

**Pull request merged**
