### PR TITLE
Make CI green again

### PR DESCRIPTION
**Pull request by mmlb**

### CODE REVIEW

**Comment by mmlb** [comment]
Fixes #58, ping @jasmingacic what do we need to fix tests?

**Comment by jasmingacic** [comment]
Basically we need to configure the CI to provide the auth token.

**Comment by obynio** [comment]
Any news on this PR ?

**Comment by mmlb** [comment]
I think i have everything needed to get to green, but have been interrupted with some things at work. I'd like to get this finished today.

**Comment by jasmingacic** [comment]
@mmlb excellent. Could you also push the latest version to pip as we need it for some ansible work.

**Pull request merged**
